# Generated by Django 4.2.3 on 2023-07-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="snippet",
            name="linenos",
            field=models.BooleanField(default=False),
        ),
    ]
